"use client";

import { useEffect, useState } from "react";
import type { EventRecord } from "../data/events";

export type DemoUser = { id: string; name: string; email: string; phone: string; city: string; bio: string; status?: "Aktif" | "Askıda"; createdAt?: string };
export type DemoEvent = EventRecord & { demo: true; description: string; capacity: number; sold: number; time: string; status: "Yayında" | "Taslak" | "İncelemede"; createdAt: string };
export type DemoSale = { id: string; orderNumber: string; eventSlug: string; eventTitle: string; buyer: string; quantity: number; total: number; createdAt: string; status: "Tamamlandı" | "İade edildi" | "Başarısız"; paymentMethod: string; installments: number };
export type DemoTicket = { id: string; orderNumber: string; eventSlug: string; eventTitle: string; category: string; place: string; city: string; date: string; time: string; seats: string[]; total: number; qr: string; status: "AKTİF" | "TRANSFER EDİLDİ" | "İADE EDİLDİ"; createdAt: string };
export type DemoOrganizer = { id: string; name: string; email: string; phone: string; city: string; taxNumber: string; commission: number; status: "Aktif" | "İncelemede" | "Askıda"; createdAt: string };
export type DemoCampaign = { id: string; name: string; code: string; kind: "Yüzde" | "Tutar"; value: number; usageLimit: number; used: number; active: boolean; createdAt: string };
export type DemoSupportTicket = { id: string; number: string; userName: string; subject: string; message: string; priority: "Normal" | "Yüksek"; status: "Açık" | "İşlemde" | "Çözüldü"; createdAt: string };
export type DemoModerationItem = { id: string; type: "Etkinlik" | "Organizatör" | "Yorum" | "İade"; title: string; reason: string; status: "Bekliyor" | "Onaylandı" | "Reddedildi"; createdAt: string };
export type DemoTeamMember = { id: string; name: string; email: string; role: "Yönetici" | "Editör" | "Finans" | "Gişe"; status: "Aktif" | "Davet edildi"; createdAt: string };
export type DemoSettings = { platformName: string; supportEmail: string; defaultCommission: number; maintenanceMode: boolean; emailNotifications: boolean; smsNotifications: boolean };

export type DemoState = { version: 3; currentUser: DemoUser; users: DemoUser[]; events: DemoEvent[]; sales: DemoSale[]; tickets: DemoTicket[]; organizers: DemoOrganizer[]; campaigns: DemoCampaign[]; supportTickets: DemoSupportTicket[]; moderation: DemoModerationItem[]; team: DemoTeamMember[]; settings: DemoSettings };

const STORAGE_KEY = "bulus-demo-state-v3";
const LEGACY_KEY = "bulus-demo-state-v2";
const CHANGE_EVENT = "bulus-demo-change";
const seedDate = "2026-08-20T09:00:00.000Z";

export function createDefaultDemoState(): DemoState {
  const currentUser: DemoUser = { id: "demo-ahmet", name: "Ahmet Yılmaz", email: "ahmet@bulus.demo", phone: "0555 111 22 33", city: "Ankara", bio: "Stand-up, konser ve yeni şehir planlarını seviyorum.", status: "Aktif", createdAt: seedDate };
  return {
    version: 3, currentUser,
    users: [currentUser, { id: "u-2", name: "Elif Kaya", email: "elif@bulus.demo", phone: "0532 200 10 20", city: "İstanbul", bio: "Konser tutkunu", status: "Aktif", createdAt: "2026-08-18T12:00:00.000Z" }, { id: "u-3", name: "Deniz Arslan", email: "deniz@bulus.demo", phone: "0544 330 40 50", city: "İzmir", bio: "Tiyatro ve sergi", status: "Aktif", createdAt: "2026-08-17T14:00:00.000Z" }, { id: "u-4", name: "Mert Şahin", email: "mert@bulus.demo", phone: "0505 600 70 80", city: "Bursa", bio: "Hafta sonu etkinlikleri", status: "Askıda", createdAt: "2026-08-16T10:00:00.000Z" }],
    events: [], sales: [], tickets: [],
    organizers: [{ id: "org-1", name: "BKM Organizasyon", email: "demo@bkm.test", phone: "0312 555 10 10", city: "Ankara", taxNumber: "1234567890", commission: 9.8, status: "Aktif", createdAt: seedDate }, { id: "org-2", name: "Nova Etkinlik A.Ş.", email: "nova@bulus.demo", phone: "0212 444 20 20", city: "İstanbul", taxNumber: "9876543210", commission: 10, status: "İncelemede", createdAt: "2026-08-19T10:00:00.000Z" }],
    campaigns: [{ id: "camp-1", name: "Erken Dönem", code: "ERKEN20", kind: "Yüzde", value: 20, usageLimit: 100, used: 36, active: true, createdAt: seedDate }, { id: "camp-2", name: "Arkadaşını Getir", code: "BIRLIKTE150", kind: "Tutar", value: 150, usageLimit: 250, used: 82, active: true, createdAt: seedDate }],
    supportTickets: [{ id: "sup-1", number: "BLŞ-D-10482", userName: "Elif Kaya", subject: "Bilet ve QR", message: "QR kodumu cüzdanda göremiyorum.", priority: "Normal", status: "Açık", createdAt: "2026-08-20T08:30:00.000Z" }, { id: "sup-2", number: "BLŞ-D-10470", userName: "Deniz Arslan", subject: "İade", message: "Test biletim için iade akışını denemek istiyorum.", priority: "Yüksek", status: "İşlemde", createdAt: "2026-08-19T15:30:00.000Z" }],
    moderation: [{ id: "mod-1", type: "Organizatör", title: "Nova Etkinlik A.Ş.", reason: "Yeni başvuru", status: "Bekliyor", createdAt: "2026-08-20T08:36:00.000Z" }, { id: "mod-2", type: "Yorum", title: "Kullanıcı bildirimi #4821", reason: "Uygunsuz içerik", status: "Bekliyor", createdAt: "2026-08-20T08:12:00.000Z" }],
    team: [{ id: "team-1", name: "Hüseyin Kılıçoğlu", email: "huseyin@bulus.demo", role: "Yönetici", status: "Aktif", createdAt: seedDate }, { id: "team-2", name: "Selin Akın", email: "selin@bulus.demo", role: "Editör", status: "Aktif", createdAt: seedDate }],
    settings: { platformName: "BULUŞ", supportEmail: "destek@bulus.demo", defaultCommission: 9.8, maintenanceMode: false, emailNotifications: true, smsNotifications: false },
  };
}

function mergeState(saved: Partial<DemoState> & { version?: number }): DemoState {
  const defaults = createDefaultDemoState(); const currentUser = saved.currentUser ?? defaults.currentUser;
  return { ...defaults, ...saved, version: 3, currentUser, users: saved.users?.length ? saved.users.map(user => user.id === currentUser.id ? currentUser : user) : [currentUser, ...defaults.users.filter(user => user.id !== currentUser.id)], events: saved.events ?? [], sales: (saved.sales ?? []).map(sale => ({ ...sale, status: sale.status || "Tamamlandı", paymentMethod: sale.paymentMethod || "Test kartı •••• 4242", installments: sale.installments || 1 })), tickets: saved.tickets ?? [], organizers: saved.organizers ?? defaults.organizers, campaigns: saved.campaigns ?? defaults.campaigns, supportTickets: saved.supportTickets ?? defaults.supportTickets, moderation: saved.moderation ?? defaults.moderation, team: saved.team ?? defaults.team, settings: { ...defaults.settings, ...(saved.settings ?? {}) } };
}

export function loadDemoState(): DemoState { if (typeof window === "undefined") return createDefaultDemoState(); try { const saved = window.localStorage.getItem(STORAGE_KEY) ?? window.localStorage.getItem(LEGACY_KEY); return saved ? mergeState(JSON.parse(saved)) : createDefaultDemoState(); } catch { return createDefaultDemoState(); } }
function persistDemoState(state: DemoState) { if (typeof window === "undefined") return; window.localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); window.dispatchEvent(new CustomEvent(CHANGE_EVENT)); }
function updateState(change: (state: DemoState) => DemoState) { const next = change(loadDemoState()); persistDemoState(next); return next; }
export function useDemoState() { const [state, setState] = useState<DemoState>(createDefaultDemoState); useEffect(() => { const refresh = () => setState(loadDemoState()); refresh(); window.addEventListener(CHANGE_EVENT, refresh); window.addEventListener("storage", refresh); return () => { window.removeEventListener(CHANGE_EVENT, refresh); window.removeEventListener("storage", refresh); }; }, []); return state; }

export function slugifyDemoEvent(title: string) { const safe = title.toLocaleLowerCase("tr-TR").replaceAll("ı", "i").replaceAll("ğ", "g").replaceAll("ü", "u").replaceAll("ş", "s").replaceAll("ö", "o").replaceAll("ç", "c").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); return `${safe || "etkinlik"}-${Date.now().toString().slice(-5)}`; }
export function addDemoEvent(input: Omit<DemoEvent, "slug" | "demo" | "sold" | "createdAt">) { const event: DemoEvent = { ...input, slug: slugifyDemoEvent(input.title), demo: true, sold: 0, createdAt: new Date().toISOString() }; updateState(current => ({ ...current, events: [event, ...current.events], moderation: event.status === "İncelemede" ? [{ id: crypto.randomUUID(), type: "Etkinlik", title: event.title, reason: "Yayın onayı", status: "Bekliyor", createdAt: event.createdAt }, ...current.moderation] : current.moderation })); return event; }
export function updateDemoEvent(slug: string, input: Partial<DemoEvent>) { updateState(current => ({ ...current, events: current.events.map(event => event.slug === slug ? { ...event, ...input } : event) })); }
export function deleteDemoEvent(slug: string) { updateState(current => ({ ...current, events: current.events.filter(event => event.slug !== slug) })); }
export function signInDemoUser(input: { name?: string; email?: string; phone?: string }) { const current = loadDemoState(); const email = input.email?.trim() || current.currentUser.email; const inferredName = email.split("@")[0].replace(/[._-]+/g, " ").replace(/\b\w/g, letter => letter.toLocaleUpperCase("tr-TR")); const currentUser: DemoUser = { ...current.currentUser, id: `demo-${email.toLocaleLowerCase("tr-TR")}`, name: input.name?.trim() || inferredName || "Demo Kullanıcı", email, phone: input.phone?.trim() || current.currentUser.phone, status: "Aktif", createdAt: current.currentUser.createdAt ?? new Date().toISOString() }; persistDemoState({ ...current, currentUser, users: [currentUser, ...current.users.filter(user => user.email !== email)] }); return currentUser; }
export function updateDemoUser(input: Partial<DemoUser>) { const current = loadDemoState(); const currentUser = { ...current.currentUser, ...input }; persistDemoState({ ...current, currentUser, users: current.users.map(user => user.id === current.currentUser.id ? currentUser : user) }); return currentUser; }
export function toggleDemoUser(id: string) { updateState(current => ({ ...current, users: current.users.map(user => user.id === id ? { ...user, status: user.status === "Askıda" ? "Aktif" : "Askıda" } : user) })); }

export function recordDemoSale(event: EventRecord, seats: string[], total: number, payment: { method?: string; installments?: number; fail?: boolean } = {}) { const current = loadDemoState(); const orderNumber = `BLŞ-D-${Math.floor(10000 + Math.random() * 89999)}`; const createdAt = new Date().toISOString(); const sale: DemoSale = { id: crypto.randomUUID(), orderNumber, eventSlug: event.slug, eventTitle: event.title, buyer: current.currentUser.name, quantity: seats.length, total, createdAt, status: payment.fail ? "Başarısız" : "Tamamlandı", paymentMethod: payment.method ?? "Test kartı •••• 4242", installments: payment.installments ?? 1 }; if (payment.fail) { persistDemoState({ ...current, sales: [sale, ...current.sales] }); return null; } const ticket: DemoTicket = { id: crypto.randomUUID(), orderNumber, eventSlug: event.slug, eventTitle: event.title, category: event.category, place: event.place, city: event.city, date: `${event.day} ${event.month}`, time: event.time || "20:30", seats, total, qr: `BLŞ-${crypto.randomUUID().slice(0, 8).toUpperCase()}`, status: "AKTİF", createdAt }; const events = current.events.map(item => item.slug === event.slug ? { ...item, sold: Math.min(item.capacity, item.sold + seats.length) } : item); persistDemoState({ ...current, events, sales: [sale, ...current.sales], tickets: [ticket, ...current.tickets] }); return ticket; }
export function refundDemoSale(id: string) { updateState(current => { const sale = current.sales.find(item => item.id === id); return { ...current, sales: current.sales.map(item => item.id === id ? { ...item, status: "İade edildi" } : item), tickets: current.tickets.map(ticket => ticket.orderNumber === sale?.orderNumber ? { ...ticket, status: "İADE EDİLDİ" } : ticket) }; }); }
export function transferDemoTicket(ticketId: string) { updateState(current => ({ ...current, tickets: current.tickets.map(ticket => ticket.id === ticketId ? { ...ticket, status: "TRANSFER EDİLDİ" } : ticket) })); }

export function addDemoOrganizer(input: Omit<DemoOrganizer, "id" | "createdAt" | "status">) { const organizer: DemoOrganizer = { ...input, id: crypto.randomUUID(), status: "İncelemede", createdAt: new Date().toISOString() }; updateState(current => ({ ...current, organizers: [organizer, ...current.organizers], moderation: [{ id: crypto.randomUUID(), type: "Organizatör", title: organizer.name, reason: "Yeni başvuru", status: "Bekliyor", createdAt: organizer.createdAt }, ...current.moderation] })); return organizer; }
export function updateDemoOrganizer(id: string, input: Partial<DemoOrganizer>) { updateState(current => { const organizer=current.organizers.find(item=>item.id===id); return { ...current, organizers: current.organizers.map(item => item.id === id ? { ...item, ...input } : item), moderation: input.status === "Aktif" ? current.moderation.map(item=>item.type==="Organizatör"&&item.title===organizer?.name?{...item,status:"Onaylandı"}:item) : current.moderation }; }); }
export function addDemoCampaign(input: Omit<DemoCampaign, "id" | "used" | "createdAt">) { const item: DemoCampaign = { ...input, id: crypto.randomUUID(), used: 0, createdAt: new Date().toISOString() }; updateState(current => ({ ...current, campaigns: [item, ...current.campaigns] })); return item; }
export function toggleDemoCampaign(id: string) { updateState(current => ({ ...current, campaigns: current.campaigns.map(item => item.id === id ? { ...item, active: !item.active } : item) })); }
export function addDemoSupportTicket(input: Pick<DemoSupportTicket, "subject" | "message">) { const current = loadDemoState(); const item: DemoSupportTicket = { ...input, id: crypto.randomUUID(), number: `BLŞ-D-${Math.floor(10000 + Math.random() * 89999)}`, userName: current.currentUser.name, priority: "Normal", status: "Açık", createdAt: new Date().toISOString() }; persistDemoState({ ...current, supportTickets: [item, ...current.supportTickets] }); return item; }
export function updateDemoSupportTicket(id: string, status: DemoSupportTicket["status"]) { updateState(current => ({ ...current, supportTickets: current.supportTickets.map(item => item.id === id ? { ...item, status } : item) })); }
export function updateDemoModeration(id: string, status: DemoModerationItem["status"]) { updateState(current => { const record=current.moderation.find(item=>item.id===id); return { ...current, moderation: current.moderation.map(item => item.id === id ? { ...item, status } : item), organizers: current.organizers.map(item=>record?.type==="Organizatör"&&item.name===record.title?{...item,status:status==="Onaylandı"?"Aktif":status==="Reddedildi"?"Askıda":"İncelemede"}:item), events: current.events.map(item=>record?.type==="Etkinlik"&&item.title===record.title?{...item,status:status==="Onaylandı"?"Yayında":"İncelemede"}:item) }; }); }
export function addDemoTeamMember(input: Pick<DemoTeamMember, "name" | "email" | "role">) { const item: DemoTeamMember = { ...input, id: crypto.randomUUID(), status: "Davet edildi", createdAt: new Date().toISOString() }; updateState(current => ({ ...current, team: [item, ...current.team] })); return item; }
export function removeDemoTeamMember(id: string) { updateState(current => ({ ...current, team: current.team.filter(item => item.id !== id) })); }
export function updateDemoSettings(input: Partial<DemoSettings>) { updateState(current => ({ ...current, settings: { ...current.settings, ...input } })); }
export function resetDemoState() { const next = createDefaultDemoState(); persistDemoState(next); return next; }
