"use client";

import { PanelShell } from "../components/PanelShell";
import { updateDemoModeration, useDemoState } from "../lib/demo-store";

function downloadReport() { const content = "BULUŞ Demo Platform Raporu\nBu belge gerçek finansal veri içermez.\nOluşturulma: " + new Date().toLocaleString("tr-TR"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([content], { type: "text/plain" })); link.download = "bulus-demo-platform-raporu.txt"; link.click(); URL.revokeObjectURL(link.href); }

export default function AdminPage() {
  const demo = useDemoState(); const revenue = demo.sales.filter(sale => sale.status === "Tamamlandı").reduce((sum,sale)=>sum+sale.total,0); const pending = demo.moderation.filter(item=>item.status==="Bekliyor");
  return <PanelShell area="admin" title="Platform kontrol merkezi" subtitle="Tüm demo ekosisteminin güncel görünümü ve bekleyen işlemler." action={<button className="panel-main-action" type="button" onClick={downloadReport}>Rapor indir ↓</button>}>
    <section className="demo-panel-strip"><div><span>🧪</span><p><strong>Tam bağlı demo yönetimi</strong><small>Kullanıcı, satış, organizatör, destek ve moderasyon verileri paneller arasında eş zamanlıdır.</small></p></div><div><a href="/admin/moderation">Bekleyenleri aç</a><a href="/organizer">Organizatör paneli</a></div></section>
    <section className="kpi-grid admin-kpis"><article><span className="kpi-icon purple">◎</span><p><small>DEMO KULLANICI</small><strong>{demo.users.length}</strong><span className="trend up">AKTİF</span><em>yerel kayıt</em></p></article><article><span className="kpi-icon orange">₺</span><p><small>DEMO SATIŞ HACMİ</small><strong>{revenue.toLocaleString("tr-TR")} <i>TL</i></strong><span className="trend up">ANLIK</span><em>gerçek para değil</em></p></article><article><span className="kpi-icon pink">◇</span><p><small>DEMO ETKİNLİK</small><strong>{demo.events.length+6}</strong><span className="trend up">{demo.events.length} YENİ</span><em>katalog toplamı</em></p></article><article><span className="kpi-icon gold">!</span><p><small>BEKLEYEN İŞLEM</small><strong>{pending.length}</strong><span className="trend alert">İNCELENECEK</span><em>moderasyon kuyruğu</em></p></article></section>
    <section className="admin-status-grid"><article className="platform-health"><div className="panel-card-head"><div><small>SİSTEM DURUMU</small><h2>Tüm demo servisleri çalışıyor</h2></div><span className="healthy">● Operasyonel</span></div><div className="service-list">{[["Kullanıcı akışı","100%","Yerel"],["Bilet servisi","100%",`${demo.tickets.length} bilet`],["Ödeme simülasyonu","100%",`${demo.sales.length} işlem`],["Destek merkezi","100%",`${demo.supportTickets.length} talep`]].map(item=><div key={item[0]}><span><i/>{item[0]}</span><b>{item[1]}</b><small>{item[2]}</small></div>)}</div></article><article className="revenue-card"><div className="panel-card-head"><div><small>PLATFORM GELİRİ</small><h2>Demo komisyon özeti</h2></div><a href="/admin/finance">Detay →</a></div><strong>{Math.round(revenue*.098).toLocaleString("tr-TR")} TL</strong><p>Ortalama komisyon <b>%9,8</b></p><div className="stacked-bar"><i/><i/><i/></div><ul><li><span className="purple-dot"/>Bilet komisyonu <b>%76</b></li><li><span className="orange-dot"/>Paketler <b>%16</b></li><li><span className="pink-dot"/>Sponsorlu <b>%8</b></li></ul></article></section>
    <section className="panel-table-card moderation-table"><div className="panel-card-head"><div><small>ÖNCELİKLİ KUYRUK</small><h2>Bekleyen işlemler</h2></div><a href="/admin/moderation">Tümünü gör →</a></div>{pending.length?<div className="panel-table"><div className="table-row table-head"><span>TÜR</span><span>KAYIT</span><span>NEDEN</span><span>EKLENDİ</span><span>İŞLEM</span></div>{pending.slice(0,4).map(item=><div className="table-row" key={item.id}><span><em className={`type-${item.type.toLocaleLowerCase("tr-TR")}`}>{item.type}</em></span><span><strong>{item.title}</strong></span><span>{item.reason}</span><span>{new Date(item.createdAt).toLocaleString("tr-TR",{timeZone:"Europe/Istanbul"})}</span><span><button type="button" onClick={()=>updateDemoModeration(item.id,"Onaylandı")}>Onayla →</button></span></div>)}</div>:<div className="guided-empty compact"><span>✓</span><h3>Kuyruk temiz</h3><p>Yeni başvurular burada görünecek.</p></div>}</section>
    <section className="admin-lower-grid"><article><div className="panel-card-head"><div><small>YÖNETİM KISAYOLLARI</small><h2>Hızlı işlemler</h2></div></div><div className="admin-shortcuts"><a href="/admin/organizers">+ Organizatör ekle</a><a href="/admin/users">Kullanıcıları yönet</a><a href="/admin/support">Destek talepleri</a><a href="/admin/settings">Sistem ayarları</a></div></article><article><div className="panel-card-head"><div><small>GÜVENLİK</small><h2>Demo ortamı</h2></div><span className="healthy">● Korunuyor</span></div><div className="security-stats"><span><strong>Yerel</strong><small>Veri saklama</small></span><span><strong>Kapalı</strong><small>Gerçek ödeme</small></span><span><strong>Kapalı</strong><small>Gerçek e-posta</small></span><span><strong>v3</strong><small>Demo sürümü</small></span></div><a href="/admin/settings">Güvenlik ayarlarını aç →</a></article></section>
  </PanelShell>;
}
