"use client";

import { useMemo, useState } from "react";
import { PanelShell } from "./PanelShell";
import { turkishCities } from "../data/cities";
import { eventRecords } from "../data/events";
import { addDemoOrganizer, refundDemoSale, toggleDemoUser, updateDemoEvent, updateDemoModeration, updateDemoOrganizer, updateDemoSettings, updateDemoSupportTicket, useDemoState } from "../lib/demo-store";

type Mode = "users" | "organizers" | "events" | "finance" | "moderation" | "support" | "settings";
const meta: Record<Mode,[string,string,string]> = {
  users:["Kullanıcı yönetimi","Demo hesaplarını görüntüle, ara ve durumlarını yönet.","Kullanıcılar"], organizers:["Organizatörler","Başvuru, komisyon ve hesap durumlarını yönet.","Organizatörler"], events:["Etkinlik yönetimi","Platformdaki içerikleri ve yayın durumlarını denetle.","Etkinlikler"], finance:["Platform finansı","Demo ödemeleri, komisyonları ve iadeleri izle.","Finans"], moderation:["Moderasyon kuyruğu","Bekleyen kayıtları incele ve karara bağla.","Moderasyon"], support:["Destek merkezi","Kullanıcı taleplerini yanıtla ve sonuçlandır.","Destek"], settings:["Sistem ayarları","Platformun demo çalışma tercihlerini yönet.","Ayarlar"],
};
function csvDownload(filename:string, rows:(string|number)[][]){const csv=rows.map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([`\ufeff${csv}`],{type:"text/csv;charset=utf-8"}));a.download=filename;a.click();URL.revokeObjectURL(a.href);}

export function AdminWorkspace({mode}:{mode:Mode}){
  const demo=useDemoState(); const [notice,setNotice]=useState(""); const [showForm,setShowForm]=useState(false); const [query,setQuery]=useState("");
  const [organizer,setOrganizer]=useState({name:"",email:"",phone:"",city:"Ankara",taxNumber:"",commission:9.8}); const [settings,setSettings]=useState(demo.settings);
  const [title,subtitle,active]=meta[mode]; const completed=demo.sales.filter(s=>s.status==="Tamamlandı"); const revenue=completed.reduce((sum,s)=>sum+s.total,0);
  const filteredUsers=demo.users.filter(user=>`${user.name} ${user.email} ${user.city}`.toLocaleLowerCase("tr-TR").includes(query.toLocaleLowerCase("tr-TR")));
  const allEvents=useMemo(()=>[...demo.events,...eventRecords],[demo.events]);
  const action=mode==="organizers"?<button type="button" className="panel-main-action" onClick={()=>setShowForm(v=>!v)}>+ Organizatör ekle</button>:mode==="finance"?<button type="button" className="panel-main-action" onClick={()=>csvDownload("bulus-platform-finans.csv",[["Sipariş","Alıcı","Tutar","Durum"],...demo.sales.map(s=>[s.orderNumber,s.buyer,s.total,s.status])])}>Finansı indir ↓</button>:undefined;
  return <PanelShell area="admin" active={active} title={title} subtitle={subtitle} action={action}>
    {notice&&<div className="panel-notice" role="status">✓ {notice}<button type="button" onClick={()=>setNotice("")}>×</button></div>}
    {mode==="users"&&<><section className="panel-summary-row"><article><small>DEMO KULLANICI</small><strong>{demo.users.length}</strong><span>{demo.users.filter(u=>u.status!=="Askıda").length} aktif hesap</span></article><article><small>YENİ KAYIT</small><strong>{demo.users.filter(u=>u.id.startsWith("demo-")).length}</strong><span>Test girişlerinden</span></article><article><small>ASKIDA</small><strong>{demo.users.filter(u=>u.status==="Askıda").length}</strong><span>Yönetici işlemi</span></article></section><section className="workspace-card"><div className="workspace-toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ad, e-posta veya şehir ara"/><span>{filteredUsers.length} sonuç</span></div><div className="data-table user-data"><div className="data-head"><span>Kullanıcı</span><span>İletişim</span><span>Şehir</span><span>Kayıt</span><span>Durum</span><span>İşlem</span></div>{filteredUsers.map(user=><div className="data-row" key={user.id}><span><strong>{user.name}</strong><small>{user.id}</small></span><span>{user.email}<small>{user.phone}</small></span><span>{user.city}</span><span>{new Date(user.createdAt??"2026-08-20T09:00:00.000Z").toLocaleDateString("tr-TR",{timeZone:"Europe/Istanbul"})}</span><span><em className={`status-pill ${user.status==="Askıda"?"bad":"ok"}`}>{user.status??"Aktif"}</em></span><span><button type="button" onClick={()=>{toggleDemoUser(user.id);setNotice(user.status==="Askıda"?"Hesap yeniden etkinleştirildi.":"Hesap demo olarak askıya alındı.")}}>{user.status==="Askıda"?"Etkinleştir":"Askıya al"}</button></span></div>)}</div></section></>}

    {mode==="organizers"&&<>{showForm&&<section className="workspace-form"><h2>Yeni organizatör kaydı</h2><p>Bu form demo başvurusu oluşturur ve otomatik olarak moderasyon kuyruğuna ekler.</p><div><label>Firma adı<input value={organizer.name} onChange={e=>setOrganizer({...organizer,name:e.target.value})}/></label><label>E-posta<input type="email" value={organizer.email} onChange={e=>setOrganizer({...organizer,email:e.target.value})}/></label><label>Telefon<input value={organizer.phone} onChange={e=>setOrganizer({...organizer,phone:e.target.value})}/></label><label>Şehir<select value={organizer.city} onChange={e=>setOrganizer({...organizer,city:e.target.value})}>{turkishCities.map(city=><option key={city}>{city}</option>)}</select></label><label>Vergi numarası<input value={organizer.taxNumber} onChange={e=>setOrganizer({...organizer,taxNumber:e.target.value})}/></label><label>Komisyon (%)<input type="number" step="0.1" value={organizer.commission} onChange={e=>setOrganizer({...organizer,commission:Number(e.target.value)})}/></label></div><footer><button type="button" onClick={()=>setShowForm(false)}>Vazgeç</button><button type="button" onClick={()=>{if(!organizer.name||!organizer.email||!organizer.taxNumber)return setNotice("Firma adı, e-posta ve vergi numarası zorunlu.");addDemoOrganizer(organizer);setShowForm(false);setNotice("Organizatör eklendi ve incelemeye gönderildi.")}}>Kaydı oluştur</button></footer></section>}<section className="panel-summary-row"><article><small>TOPLAM</small><strong>{demo.organizers.length}</strong><span>Kayıtlı demo firma</span></article><article><small>AKTİF</small><strong>{demo.organizers.filter(o=>o.status==="Aktif").length}</strong><span>Etkinlik yayınlayabilir</span></article><article><small>İNCELEMEDE</small><strong>{demo.organizers.filter(o=>o.status==="İncelemede").length}</strong><span>Onay bekliyor</span></article></section><section className="workspace-card"><div className="data-table organizer-data"><div className="data-head"><span>Firma</span><span>İletişim</span><span>Şehir</span><span>Komisyon</span><span>Durum</span><span>İşlem</span></div>{demo.organizers.map(item=><div className="data-row" key={item.id}><span><strong>{item.name}</strong><small>VN: {item.taxNumber}</small></span><span>{item.email}<small>{item.phone}</small></span><span>{item.city}</span><span>%{item.commission}</span><span><em className={`status-pill ${item.status==="Aktif"?"ok":item.status==="Askıda"?"bad":"wait"}`}>{item.status}</em></span><span><button type="button" onClick={()=>{updateDemoOrganizer(item.id,{status:item.status==="Aktif"?"Askıda":"Aktif"});setNotice("Organizatör durumu güncellendi.")}}>{item.status==="Aktif"?"Askıya al":"Onayla"}</button></span></div>)}</div></section></>}

    {mode==="events"&&<><section className="panel-summary-row"><article><small>TOPLAM ETKİNLİK</small><strong>{allEvents.length}</strong><span>{demo.events.length} demo kaydı</span></article><article><small>YAYINDA</small><strong>{allEvents.filter(e=>!e.demo||e.status==="Yayında").length}</strong><span>Kullanıcıya görünür</span></article><article><small>İNCELEMEDE</small><strong>{demo.events.filter(e=>e.status==="İncelemede").length}</strong><span>Admin kararı bekliyor</span></article></section><section className="workspace-card"><div className="workspace-toolbar"><h2>Etkinlik kataloğu</h2><a href="/organizer/events/new">Test etkinliği ekle ↗</a></div><div className="data-table admin-event-data"><div className="data-head"><span>Etkinlik</span><span>Kategori</span><span>Tarih / şehir</span><span>Fiyat</span><span>Durum</span><span>İşlem</span></div>{allEvents.map(event=><div className="data-row" key={event.slug}><span><strong>{event.title}</strong><small>{event.artist}</small></span><span>{event.category}</span><span>{event.day} {event.month}<small>{event.city}</small></span><span>{event.price.toLocaleString("tr-TR")} TL</span><span><em className={`status-pill ${!event.demo||event.status==="Yayında"?"ok":"wait"}`}>{event.demo?event.status:"Yayında"}</em></span><span>{event.demo?<button type="button" onClick={()=>{updateDemoEvent(event.slug,{status:event.status==="Yayında"?"Taslak":"Yayında"});setNotice("Yayın durumu değiştirildi.")}}>{event.status==="Yayında"?"Yayından al":"Onayla"}</button>:<a href={`/event/${event.slug}`}>İncele</a>}</span></div>)}</div></section></>}

    {mode==="finance"&&<><section className="panel-summary-row"><article><small>DEMO HACİM</small><strong>{revenue.toLocaleString("tr-TR")} TL</strong><span>Gerçek para değildir</span></article><article><small>PLATFORM PAYI</small><strong>{Math.round(revenue*.098).toLocaleString("tr-TR")} TL</strong><span>Ortalama %9,8</span></article><article><small>BAŞARISIZ</small><strong>{demo.sales.filter(s=>s.status==="Başarısız").length}</strong><span>Ödeme simülasyonu</span></article></section><section className="workspace-card"><div className="workspace-toolbar"><h2>Tüm ödeme denemeleri</h2><a href="/discover">Yeni test ödemesi ↗</a></div>{demo.sales.length?<div className="data-table finance-data"><div className="data-head"><span>Sipariş</span><span>Alıcı</span><span>Yöntem</span><span>Tutar</span><span>Durum</span><span>İşlem</span></div>{demo.sales.map(sale=><div className="data-row" key={sale.id}><span><strong>{sale.orderNumber}</strong><small>{new Date(sale.createdAt).toLocaleString("tr-TR",{timeZone:"Europe/Istanbul"})}</small></span><span>{sale.buyer}</span><span>{sale.paymentMethod}<small>{sale.installments} taksit</small></span><span><b>{sale.total.toLocaleString("tr-TR")} TL</b></span><span><em className={`status-pill ${sale.status==="Tamamlandı"?"ok":sale.status==="Başarısız"?"bad":"wait"}`}>{sale.status}</em></span><span>{sale.status==="Tamamlandı"?<button type="button" onClick={()=>{refundDemoSale(sale.id);setNotice("Demo iadesi tamamlandı.")}}>İade et</button>:<span>Kapalı</span>}</span></div>)}</div>:<div className="guided-empty"><span>₺</span><h3>Henüz ödeme denemesi yok</h3><p>Kullanıcı tarafında başarılı veya başarısız test ödemesi yap; bütün ayrıntı burada görünür.</p><a href="/discover">Ödeme simülasyonuna git</a></div>}</section></>}

    {mode==="moderation"&&<><section className="panel-summary-row"><article><small>BEKLEYEN</small><strong>{demo.moderation.filter(m=>m.status==="Bekliyor").length}</strong><span>Karar gerektiren kayıt</span></article><article><small>ONAYLANAN</small><strong>{demo.moderation.filter(m=>m.status==="Onaylandı").length}</strong><span>Bu demo oturumunda</span></article><article><small>REDDEDİLEN</small><strong>{demo.moderation.filter(m=>m.status==="Reddedildi").length}</strong><span>Gerekçeli karar</span></article></section><section className="workspace-card"><div className="data-table moderation-data"><div className="data-head"><span>Tür</span><span>Kayıt</span><span>Neden</span><span>Tarih</span><span>Durum</span><span>Karar</span></div>{demo.moderation.map(item=><div className="data-row" key={item.id}><span>{item.type}</span><span><strong>{item.title}</strong></span><span>{item.reason}</span><span>{new Date(item.createdAt).toLocaleString("tr-TR",{timeZone:"Europe/Istanbul"})}</span><span><em className={`status-pill ${item.status==="Onaylandı"?"ok":item.status==="Reddedildi"?"bad":"wait"}`}>{item.status}</em></span><span>{item.status==="Bekliyor"?<><button type="button" onClick={()=>{updateDemoModeration(item.id,"Onaylandı");setNotice("Kayıt onaylandı.")}}>Onayla</button><button className="danger-link" type="button" onClick={()=>{updateDemoModeration(item.id,"Reddedildi");setNotice("Kayıt reddedildi.")}}>Reddet</button></>:<button type="button" onClick={()=>updateDemoModeration(item.id,"Bekliyor")}>Geri al</button>}</span></div>)}</div></section></>}

    {mode==="support"&&<><section className="panel-summary-row"><article><small>AÇIK</small><strong>{demo.supportTickets.filter(t=>t.status==="Açık").length}</strong><span>Yeni talep</span></article><article><small>İŞLEMDE</small><strong>{demo.supportTickets.filter(t=>t.status==="İşlemde").length}</strong><span>Temsilci üzerinde</span></article><article><small>ÇÖZÜLDÜ</small><strong>{demo.supportTickets.filter(t=>t.status==="Çözüldü").length}</strong><span>Tamamlanan</span></article></section><section className="support-admin-grid">{demo.supportTickets.map(ticket=><article key={ticket.id}><header><span>{ticket.number}</span><em className={`status-pill ${ticket.status==="Çözüldü"?"ok":ticket.priority==="Yüksek"?"bad":"wait"}`}>{ticket.status}</em></header><h2>{ticket.subject}</h2><strong>{ticket.userName}</strong><p>{ticket.message}</p><small>{new Date(ticket.createdAt).toLocaleString("tr-TR",{timeZone:"Europe/Istanbul"})} · {ticket.priority} öncelik</small><footer>{ticket.status!=="İşlemde"&&ticket.status!=="Çözüldü"&&<button type="button" onClick={()=>updateDemoSupportTicket(ticket.id,"İşlemde")}>Üzerime al</button>}{ticket.status!=="Çözüldü"&&<button type="button" onClick={()=>{updateDemoSupportTicket(ticket.id,"Çözüldü");setNotice("Talep çözüldü olarak işaretlendi.")}}>Çözüldü</button>}{ticket.status==="Çözüldü"&&<button type="button" onClick={()=>updateDemoSupportTicket(ticket.id,"Açık")}>Yeniden aç</button>}</footer></article>)}</section></>}

    {mode==="settings"&&<section className="settings-grid"><form className="workspace-form" onSubmit={e=>{e.preventDefault();updateDemoSettings(settings);setNotice("Sistem ayarları kaydedildi.")}}><h2>Genel ayarlar</h2><label>Platform adı<input value={settings.platformName} onChange={e=>setSettings({...settings,platformName:e.target.value})}/></label><label>Destek e-postası<input type="email" value={settings.supportEmail} onChange={e=>setSettings({...settings,supportEmail:e.target.value})}/></label><label>Varsayılan komisyon (%)<input type="number" step="0.1" value={settings.defaultCommission} onChange={e=>setSettings({...settings,defaultCommission:Number(e.target.value)})}/></label><label className="switch-line"><input type="checkbox" checked={settings.emailNotifications} onChange={e=>setSettings({...settings,emailNotifications:e.target.checked})}/><span><strong>E-posta bildirimleri</strong><small>Demo işlem özetleri</small></span></label><label className="switch-line"><input type="checkbox" checked={settings.smsNotifications} onChange={e=>setSettings({...settings,smsNotifications:e.target.checked})}/><span><strong>SMS bildirimleri</strong><small>Gerçek SMS gönderilmez</small></span></label><label className="switch-line danger-zone"><input type="checkbox" checked={settings.maintenanceMode} onChange={e=>setSettings({...settings,maintenanceMode:e.target.checked})}/><span><strong>Bakım modu simülasyonu</strong><small>Yalnızca admin bilgisinde görünür</small></span></label><button type="submit">Ayarları kaydet</button></form><aside className="settings-info"><span>🧪</span><h2>Güvenli demo ortamı</h2><p>Bu ekrandaki ayarlar yalnızca bu tarayıcıda saklanır. Gerçek kullanıcıya bildirim gitmez, gerçek ödeme veya bakım işlemi yapılmaz.</p><ul><li>Yerel veri saklama <b>Aktif</b></li><li>Gerçek ödeme bağlantısı <b>Kapalı</b></li><li>Gerçek e-posta / SMS <b>Kapalı</b></li><li>Demo veri sürümü <b>v3</b></li></ul><a href="/admin/moderation">Sistem kontrolüne git →</a></aside></section>}
  </PanelShell>;
}
