"use client";

import { useMemo, useState } from "react";
import { PanelShell } from "./PanelShell";
import { addDemoCampaign, addDemoTeamMember, deleteDemoEvent, refundDemoSale, removeDemoTeamMember, toggleDemoCampaign, updateDemoEvent, useDemoState, type DemoTeamMember } from "../lib/demo-store";

type Mode = "events" | "tickets" | "sales" | "campaigns" | "finance" | "reports" | "team";
const meta: Record<Mode, [string, string, string]> = {
  events: ["Etkinlikler", "Etkinliklerini yayınla, durdur ve satış durumunu izle.", "Etkinlikler"],
  tickets: ["Bilet yönetimi", "Kategori, kapasite ve doluluk bilgilerini tek ekrandan yönet.", "Biletler"],
  sales: ["Satışlar", "Siparişleri incele ve demo iade akışını test et.", "Satışlar"],
  campaigns: ["Kampanyalar", "İndirim kodlarını oluştur, kullanımını izle ve durdur.", "Kampanyalar"],
  finance: ["Finans", "Tahsilat, komisyon, iade ve demo ödeme takibini yap.", "Finans"],
  reports: ["Raporlar", "Etkinlik performansını analiz et ve veriyi dışa aktar.", "Raporlar"],
  team: ["Takım ve yetkiler", "Ekip arkadaşlarını davet et ve rollerini yönet.", "Takım"],
};
const samples = [
  { title: "Mesut Süre — İlişki Testi", date: "12 Eyl 2026", city: "Ankara", sold: 1250, capacity: 1600, revenue: 562500, status: "Yayında" },
  { title: "Mabel Matiz — Fatih Turnesi", date: "21 Eyl 2026", city: "Ankara", sold: 2840, capacity: 3200, revenue: 2527600, status: "Yayında" },
  { title: "Bir Delinin Hatıra Defteri", date: "28 Eyl 2026", city: "Ankara", sold: 680, capacity: 900, revenue: 408000, status: "Yayında" },
];

function csvDownload(filename: string, rows: (string | number)[][]) {
  const csv = rows.map(row => row.map(value => `"${String(value).replaceAll('"', '""')}"`).join(",")).join("\n");
  const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([`\ufeff${csv}`], { type: "text/csv;charset=utf-8" })); link.download = filename; link.click(); URL.revokeObjectURL(link.href);
}

export function OrganizerWorkspace({ mode }: { mode: Mode }) {
  const demo = useDemoState(); const [notice, setNotice] = useState(""); const [showForm, setShowForm] = useState(false);
  const [campaign, setCampaign] = useState({ name: "", code: "", kind: "Yüzde" as "Yüzde" | "Tutar", value: 20, usageLimit: 100 });
  const [member, setMember] = useState({ name: "", email: "", role: "Editör" as DemoTeamMember["role"] });
  const [title, subtitle, active] = meta[mode];
  const completedSales = demo.sales.filter(sale => sale.status === "Tamamlandı"); const revenue = completedSales.reduce((sum, sale) => sum + sale.total, 0); const sold = completedSales.reduce((sum, sale) => sum + sale.quantity, 0);
  const allEvents = useMemo(() => [...demo.events.map(event => ({ title: event.title, date: `${event.day} ${event.month} 2026`, city: event.city, sold: event.sold, capacity: event.capacity, revenue: demo.sales.filter(sale => sale.eventSlug === event.slug && sale.status === "Tamamlandı").reduce((sum, sale) => sum + sale.total, 0), status: event.status, slug: event.slug, demo: true })), ...samples], [demo.events, demo.sales]);
  const action = mode === "events" ? <a className="panel-main-action" href="/organizer/events/new">+ Yeni etkinlik</a> : mode === "reports" ? <button className="panel-main-action" type="button" onClick={() => csvDownload("bulus-organizator-raporu.csv", [["Etkinlik", "Satılan", "Gelir"], ...allEvents.map(item => [item.title, item.sold, item.revenue])])}>Raporu indir ↓</button> : (mode === "campaigns" || mode === "team") ? <button className="panel-main-action" type="button" onClick={() => setShowForm(value => !value)}>+ {mode === "team" ? "Ekip üyesi" : "Kampanya"}</button> : undefined;

  return <PanelShell active={active} title={title} subtitle={subtitle} action={action}>
    {notice && <div className="panel-notice" role="status">✓ {notice}<button type="button" onClick={() => setNotice("")}>×</button></div>}
    {mode === "events" && <><section className="panel-summary-row"><article><small>TOPLAM ETKİNLİK</small><strong>{allEvents.length}</strong><span>{demo.events.length} tanesi senin test kaydın</span></article><article><small>YAYINDA</small><strong>{allEvents.filter(item => item.status === "Yayında").length}</strong><span>Satışa açık etkinlik</span></article><article><small>TOPLAM DOLULUK</small><strong>%{Math.round(allEvents.reduce((sum,item) => sum + item.sold,0) / allEvents.reduce((sum,item) => sum + item.capacity,0) * 100)}</strong><span>Tüm etkinlikler</span></article></section><section className="workspace-card"><div className="workspace-toolbar"><input placeholder="Etkinlik ara" onChange={event => { const value = event.target.value.toLocaleLowerCase("tr-TR"); document.querySelectorAll<HTMLElement>("[data-event-row]").forEach(row => row.hidden = !row.dataset.eventRow?.includes(value)); }} /><a href="/discover">Kullanıcı görünümü ↗</a></div><div className="data-table"><div className="data-head"><span>Etkinlik</span><span>Tarih / şehir</span><span>Doluluk</span><span>Gelir</span><span>Durum</span><span>İşlem</span></div>{allEvents.map(item => <div className="data-row" data-event-row={item.title.toLocaleLowerCase("tr-TR")} key={`${item.title}-${item.date}`}><span><strong>{item.title}</strong><small>{item.demo ? "Demo etkinliği" : "Örnek portföy"}</small></span><span>{item.date}<small>{item.city}</small></span><span>{item.sold} / {item.capacity}<small>%{Math.round(item.sold / item.capacity * 100)}</small></span><span><b>{item.revenue.toLocaleString("tr-TR")} TL</b></span><span><em className={`status-pill ${item.status === "Yayında" ? "ok" : "wait"}`}>{item.status}</em></span><span>{item.demo ? <><button type="button" onClick={() => { updateDemoEvent(item.slug!, { status: item.status === "Yayında" ? "Taslak" : "Yayında" }); setNotice("Etkinlik durumu güncellendi."); }}>{item.status === "Yayında" ? "Durdur" : "Yayınla"}</button><button className="danger-link" type="button" onClick={() => { if (confirm("Bu demo etkinliği silinsin mi?")) deleteDemoEvent(item.slug!); }}>Sil</button></> : <a href="/discover">Görüntüle</a>}</span></div>)}</div></section></>}

    {mode === "tickets" && <><section className="panel-summary-row"><article><small>SATILAN BİLET</small><strong>{sold + 4770}</strong><span>{sold} yeni demo satışı</span></article><article><small>AKTİF KATEGORİ</small><strong>9</strong><span>VIP, A ve B kategori</span></article><article><small>ORTALAMA FİYAT</small><strong>{sold ? Math.round(revenue / sold).toLocaleString("tr-TR") : "648"} TL</strong><span>Hizmet bedeli hariç</span></article></section><section className="workspace-card"><div className="workspace-toolbar"><h2>Bilet kategorileri</h2><a href="/organizer/events/new">Yeni kategori ekle →</a></div><div className="data-table ticket-data"><div className="data-head"><span>Etkinlik / kategori</span><span>Fiyat</span><span>Satılan</span><span>Kalan</span><span>Doluluk</span><span>Durum</span></div>{samples.flatMap((item,index) => [["VIP", item.revenue/item.sold+900, Math.round(item.sold*.12), Math.round(item.capacity*.12)], [index ? "Standart" : "A Kategori", item.revenue/item.sold, Math.round(item.sold*.88), Math.round(item.capacity*.88)]].map(cat => <div className="data-row" key={`${item.title}-${cat[0]}`}><span><strong>{item.title}</strong><small>{cat[0]}</small></span><span>{Math.round(Number(cat[1])).toLocaleString("tr-TR")} TL</span><span>{cat[2]}</span><span>{Number(cat[3])-Number(cat[2])}</span><span>%{Math.round(Number(cat[2])/Number(cat[3])*100)}</span><span><em className="status-pill ok">Satışta</em></span></div>))}</div></section></>}

    {mode === "sales" && <><section className="panel-summary-row"><article><small>DEMO SİPARİŞ</small><strong>{demo.sales.length}</strong><span>Bu tarayıcıdaki işlemler</span></article><article><small>DEMO CİRO</small><strong>{revenue.toLocaleString("tr-TR")} TL</strong><span>Gerçek tahsilat değildir</span></article><article><small>İADE</small><strong>{demo.sales.filter(item => item.status === "İade edildi").length}</strong><span>Simüle edilen işlem</span></article></section><section className="workspace-card"><div className="workspace-toolbar"><h2>Son siparişler</h2><a href="/discover">Test satışı yap →</a></div>{demo.sales.length ? <div className="data-table"><div className="data-head"><span>Sipariş</span><span>Etkinlik</span><span>Alıcı</span><span>Tutar</span><span>Durum</span><span>İşlem</span></div>{demo.sales.map(sale => <div className="data-row" key={sale.id}><span><strong>{sale.orderNumber}</strong><small>{new Date(sale.createdAt).toLocaleString("tr-TR",{timeZone:"Europe/Istanbul"})}</small></span><span>{sale.eventTitle}<small>{sale.quantity} bilet</small></span><span>{sale.buyer}</span><span><b>{sale.total.toLocaleString("tr-TR")} TL</b></span><span><em className={`status-pill ${sale.status === "Tamamlandı" ? "ok" : sale.status === "Başarısız" ? "bad" : "wait"}`}>{sale.status}</em></span><span>{sale.status === "Tamamlandı" ? <button type="button" onClick={() => { refundDemoSale(sale.id); setNotice("Demo iadesi işlendi ve bilet iptal edildi."); }}>Demo iade</button> : <span>İşlem kapalı</span>}</span></div>)}</div> : <div className="guided-empty"><span>↗</span><h3>Henüz demo sipariş yok</h3><p>Keşfet'ten bir etkinlik seçip test kartıyla satış yaptığında sipariş burada görünür.</p><a href="/discover">İlk test satışını yap</a></div>}</section></>}

    {mode === "campaigns" && <>{showForm && <section className="workspace-form"><h2>Yeni kampanya</h2><div><label>Kampanya adı<input value={campaign.name} onChange={e => setCampaign({...campaign,name:e.target.value})} /></label><label>Kupon kodu<input value={campaign.code} onChange={e => setCampaign({...campaign,code:e.target.value.toLocaleUpperCase("tr-TR")})} /></label><label>İndirim tipi<select value={campaign.kind} onChange={e => setCampaign({...campaign,kind:e.target.value as "Yüzde"|"Tutar"})}><option>Yüzde</option><option>Tutar</option></select></label><label>Değer<input type="number" value={campaign.value} onChange={e => setCampaign({...campaign,value:Number(e.target.value)})} /></label><label>Kullanım limiti<input type="number" value={campaign.usageLimit} onChange={e => setCampaign({...campaign,usageLimit:Number(e.target.value)})} /></label></div><footer><button type="button" onClick={() => setShowForm(false)}>Vazgeç</button><button type="button" onClick={() => { if (!campaign.name || !campaign.code) return setNotice("Kampanya adı ve kodu zorunlu."); addDemoCampaign({...campaign,active:true}); setShowForm(false); setCampaign({...campaign,name:"",code:""}); setNotice("Kampanya oluşturuldu."); }}>Kampanyayı kaydet</button></footer></section>}<section className="campaign-grid workspace-campaigns">{demo.campaigns.map(item => <article key={item.id}><div><span>{item.kind === "Yüzde" ? `%${item.value}` : `${item.value} TL`}</span><em className={`status-pill ${item.active ? "ok" : "wait"}`}>{item.active ? "Aktif" : "Durduruldu"}</em></div><h2>{item.name}</h2><code>{item.code}</code><p>{item.used} / {item.usageLimit} kullanım</p><progress value={item.used} max={item.usageLimit} /><button type="button" onClick={() => toggleDemoCampaign(item.id)}>{item.active ? "Kampanyayı durdur" : "Yeniden başlat"}</button></article>)}</section></>}

    {mode === "finance" && <><section className="finance-hero"><div><small>KULLANILABİLİR DEMO BAKİYE</small><strong>{Math.round(revenue*.902).toLocaleString("tr-TR")} TL</strong><span>Bir sonraki örnek ödeme: 31 Ağustos 2026</span></div><button type="button" onClick={() => { setNotice("Demo ödeme talebi oluşturuldu. Gerçek para hareketi yapılmadı."); }}>Demo ödeme talep et</button></section><section className="panel-summary-row"><article><small>BRÜT SATIŞ</small><strong>{revenue.toLocaleString("tr-TR")} TL</strong><span>Başarılı test ödemeleri</span></article><article><small>KOMİSYON</small><strong>{Math.round(revenue*.098).toLocaleString("tr-TR")} TL</strong><span>%9,8 platform payı</span></article><article><small>İADE</small><strong>{demo.sales.filter(item => item.status === "İade edildi").reduce((sum,item)=>sum+item.total,0).toLocaleString("tr-TR")} TL</strong><span>Demo iade toplamı</span></article></section><section className="workspace-card"><div className="workspace-toolbar"><h2>Ödeme hareketleri</h2><button type="button" onClick={() => csvDownload("bulus-finans.csv", [["Sipariş","Tutar","Durum"],...demo.sales.map(s=>[s.orderNumber,s.total,s.status])])}>CSV indir</button></div>{demo.sales.length ? <div className="data-table finance-data"><div className="data-head"><span>Tarih</span><span>İşlem</span><span>Yöntem</span><span>Brüt</span><span>Net</span><span>Durum</span></div>{demo.sales.map(sale => <div className="data-row" key={sale.id}><span>{new Date(sale.createdAt).toLocaleDateString("tr-TR",{timeZone:"Europe/Istanbul"})}</span><span><strong>{sale.orderNumber}</strong><small>{sale.eventTitle}</small></span><span>{sale.paymentMethod}<small>{sale.installments} taksit</small></span><span>{sale.total.toLocaleString("tr-TR")} TL</span><span>{Math.round(sale.total*.902).toLocaleString("tr-TR")} TL</span><span><em className={`status-pill ${sale.status === "Tamamlandı" ? "ok" : "wait"}`}>{sale.status}</em></span></div>)}</div> : <div className="guided-empty"><span>₺</span><h3>Finans hareketi satışla oluşur</h3><p>Demo ödeme yaptığında brüt, komisyon ve net tutar otomatik hesaplanır.</p><a href="/discover">Test ödemesi yap</a></div>}</section></>}

    {mode === "reports" && <><section className="report-filter"><label>Dönem<select><option>Son 30 gün</option><option>Bu çeyrek</option><option>2026 yılı</option></select></label><label>Etkinlik<select><option>Tüm etkinlikler</option>{allEvents.map(item=><option key={item.title}>{item.title}</option>)}</select></label><button type="button" onClick={() => setNotice("Rapor filtreleri uygulandı.")}>Raporu güncelle</button></section><section className="panel-summary-row"><article><small>TOPLAM BİLET</small><strong>{4770+sold}</strong><span>↗ %14,2 büyüme</span></article><article><small>TOPLAM CİRO</small><strong>{(3498100+revenue).toLocaleString("tr-TR")} TL</strong><span>↗ %11,8 büyüme</span></article><article><small>ORT. DOLULUK</small><strong>%82</strong><span>Hedefin 7 puan üstü</span></article></section><section className="workspace-card report-card"><h2>Satış performansı</h2><div className="report-bars">{[52,68,61,74,83,76,94].map((height,index)=><div key={index}><span style={{height:`${height}%`}} /><small>{["Pzt","Sal","Çar","Per","Cum","Cmt","Paz"][index]}</small></div>)}</div></section></>}

    {mode === "team" && <>{showForm && <section className="workspace-form"><h2>Ekip üyesi davet et</h2><div><label>Ad soyad<input value={member.name} onChange={e=>setMember({...member,name:e.target.value})} /></label><label>E-posta<input type="email" value={member.email} onChange={e=>setMember({...member,email:e.target.value})} /></label><label>Rol<select value={member.role} onChange={e=>setMember({...member,role:e.target.value as DemoTeamMember["role"]})}><option>Yönetici</option><option>Editör</option><option>Finans</option><option>Gişe</option></select></label></div><footer><button type="button" onClick={()=>setShowForm(false)}>Vazgeç</button><button type="button" onClick={()=>{if(!member.name||!member.email)return setNotice("Ad ve e-posta zorunlu.");addDemoTeamMember(member);setShowForm(false);setNotice("Demo daveti gönderildi.");}}>Daveti gönder</button></footer></section>}<section className="workspace-card"><div className="workspace-toolbar"><h2>Ekip üyeleri</h2><span>{demo.team.length} kişi</span></div><div className="member-grid">{demo.team.map(item=><article key={item.id}><span>{item.name.split(" ").map(word=>word[0]).slice(0,2).join("")}</span><div><strong>{item.name}</strong><small>{item.email}</small></div><em>{item.role}</em><i className={`status-pill ${item.status === "Aktif" ? "ok" : "wait"}`}>{item.status}</i>{item.role === "Yönetici" ? <b>Ana hesap</b> : <button type="button" onClick={()=>{if(confirm("Ekip üyesi kaldırılsın mı?"))removeDemoTeamMember(item.id)}}>Kaldır</button>}</article>)}</div></section></>}
  </PanelShell>;
}
