"use client";
import { useRef,useState } from "react";
import { signInDemoUser } from "../../lib/demo-store";

export default function LoginPage(){
  const [method,setMethod]=useState<"email"|"otp">("email"),[sent,setSent]=useState(false),[message,setMessage]=useState(""),[reset,setReset]=useState(false); const emailRef=useRef<HTMLInputElement>(null),phoneRef=useRef<HTMLInputElement>(null);
  function login(){const email=emailRef.current?.value.trim()||"ahmet@bulus.demo",phone=phoneRef.current?.value.trim()||"0555 111 22 33";if(method==="email"&&!email.includes("@"))return setMessage("Geçerli bir demo e-posta adresi yazmalısın.");if(method==="otp"&&phone.replace(/\D/g,"").length<10)return setMessage("Telefon numarasını kontrol etmelisin.");signInDemoUser(method==="email"?{email}:{phone,email:`${phone.replace(/\D/g,"")}@telefon.demo`});window.location.href="/profile"}
  return <main className="auth-page"><section className="auth-visual"><a className="brand" href="/"><span className="brand-dot">b</span><span>BULUŞ</span></a><div><span>ŞEHRİNLE BULUŞ</span><h1>Planlar burada<br/><em>başlıyor.</em></h1><p>Demo hesabına gir; profilini düzenle, etkinlik ekle ve test bileti satın al.</p></div><small>Yerel demo modu · Gerçek giriş yapılmaz</small></section><section className="auth-form"><div><span className="section-kicker">ÇALIŞAN DEMO GİRİŞİ</span><h2>Hesabına giriş yap</h2><p>Henüz üye değil misin? <a href="/auth/register">Demo hesap oluştur</a></p><div className="demo-mode-note">🧪 İstediğin bilgileri kullanabilirsin. Gerçek doğrulama mesajı gönderilmez.</div><div className="auth-method"><button className={method==="email"?"active":""} onClick={()=>{setMethod("email");setMessage("")}} type="button">E-posta</button><button className={method==="otp"?"active":""} onClick={()=>{setMethod("otp");setMessage("")}} type="button">Telefon OTP</button></div>{method==="email"?<><label>E-posta<input ref={emailRef} type="email" defaultValue="ahmet@bulus.demo"/></label><label>Demo şifre<input type="password" defaultValue="bulus123"/><button className="inline-link" type="button" onClick={()=>setReset(true)}>Şifremi unuttum</button></label>{reset&&<div className="demo-otp">Demo sıfırlama bağlantısı hazır. Gerçek e-posta gönderilmedi. <button type="button" onClick={()=>setReset(false)}>Kapat</button></div>}<button className="auth-submit" onClick={login} type="button">Demo hesaba gir →</button></>:!sent?<><label>Telefon numarası<input ref={phoneRef} defaultValue="0555 111 22 33"/></label><button className="auth-submit" type="button" onClick={()=>setSent(true)}>Demo kodu göster →</button></>:<><div className="demo-otp">Doğrulama kodun: <strong>123456</strong></div><label>6 haneli doğrulama kodu<input inputMode="numeric" defaultValue="123456"/></label><button className="auth-submit" onClick={login} type="button">Doğrula ve profile gir →</button></>}{message&&<p className="auth-error">{message}</p>}<div className="auth-divider"><span>hızlı test</span></div><div className="social-auth"><button onClick={()=>{signInDemoUser({name:"Google Demo",email:"google@bulus.demo"});window.location.href="/profile"}} type="button">G <span>Google demo</span></button><button onClick={()=>{signInDemoUser({name:"Apple Demo",email:"apple@bulus.demo"});window.location.href="/profile"}} type="button">● <span>Apple demo</span></button></div></div></section></main>
}
