"use client";

import { useState } from "react";
import { SubHeader } from "../components/SubHeader";
import { addDemoSupportTicket } from "../lib/demo-store";

export default function SupportPage() {
  const [sent, setSent] = useState(""); const [category,setCategory]=useState("Biletlerim"); const [subject,setSubject]=useState("Bilet ve QR"); const [message,setMessage]=useState(""); const [search,setSearch]=useState(""); const [error,setError]=useState("");
  const faqs=["Biletimi nasıl transfer ederim?","İade talebi nasıl oluşturulur?","QR kodum ne zaman aktif olur?","Koltuk rezervasyonu neden 15 dakika?"].filter(item=>item.toLocaleLowerCase("tr-TR").includes(search.toLocaleLowerCase("tr-TR"))||!search);
  return <main className="utility-page"><SubHeader /><section className="support-hero"><span className="section-kicker">YARDIM MERKEZİ</span><h1>Nasıl yardımcı olabiliriz?</h1><p>Bilet, ödeme, iade ve hesabınla ilgili yanıtları hızlıca bul.</p><label><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Sorunu veya sipariş numaranı ara" /></label></section><section className="support-layout"><div><div className="support-categories">{[["▣","Biletlerim"],["₺","Ödeme ve iade"],["↗","Transfer"],["○","Hesabım"]].map(item => <button className={category===item[1]?"active":""} onClick={()=>setCategory(item[1])} type="button" key={item[1]}><span>{item[0]}</span><b>{item[1]}</b><small>{category===item[1]?"Seçildi ✓":"Yardım konularını gör →"}</small></button>)}</div><article className="faq-card"><span className="section-kicker">{category.toLocaleUpperCase("tr-TR")} · SIK SORULANLAR</span>{faqs.length?faqs.map(item => <details key={item}><summary>{item}<span>＋</span></summary><p>İlgili işlemi Biletlerim alanından başlatabilir, durumunu aynı ekrandan takip edebilirsin. Bu demo ortamında gerçek ödeme veya kimlik doğrulama yapılmaz.</p></details>):<div className="guided-empty compact"><h3>Bu aramayla sonuç yok</h3><p>Sağdaki formdan doğrudan destek talebi oluşturabilirsin.</p></div>}</article></div><aside className="support-ticket">{sent ? <div className="support-sent"><span>✓</span><small>TALEP OLUŞTURULDU</small><h2>Ekibimiz inceliyor.</h2><p>Destek numaran: <b>{sent}</b><br />Talep admin destek ekranına anında eklendi.</p><div className="support-result-links"><a href="/admin/support">Admin panelinde gör →</a><button onClick={() => {setSent("");setMessage("")}} type="button">Yeni talep oluştur</button></div></div> : <><span className="section-kicker">BİZE YAZ</span><h2>Destek talebi oluştur</h2><p>Ortalama demo yanıt süresi 2 saat.</p><label>Konu<select value={subject} onChange={e=>setSubject(e.target.value)}><option>Bilet ve QR</option><option>Ödeme</option><option>İade</option><option>Hesap</option></select></label><label>Sipariş numarası<input placeholder="BLŞ-D-10482 (isteğe bağlı)" /></label><label>Mesaj<textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Yaşadığın durumu kısaca anlat" /></label>{error&&<small className="form-error">{error}</small>}<button onClick={() => {if(message.trim().length<10){setError("Lütfen en az 10 karakterlik bir açıklama yaz.");return;}const ticket=addDemoSupportTicket({subject,message});setError("");setSent(ticket.number)}} type="button">Talebi gönder →</button><small>🧪 Talep yalnızca bu demo tarayıcısında saklanır.</small></>}</aside></section></main>;
}
